trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/**
 
pool:
  vmImage: ubuntu-latest
 
variables:
  buildConfiguration: Release
  projectPath: backend/StudentApi.csproj
 
stages:
- stage: Build
  displayName: Build Backend
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 8.x
 
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(projectPath)
 
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: $(projectPath)
        arguments: --configuration $(buildConfiguration)
 
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        projects: $(projectPath)
        arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
        zipAfterPublish: true
 
    - task: PublishBuildArtifacts@1
      displayName: Upload Artifact
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: backend-drop
 
- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        artifactName: backend-drop
        downloadPath: $(System.ArtifactsDirectory)
 
    - task: AzureWebApp@1
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: Azure-Connection
        appType: webAppLinux
        appName: weather-webapp
        package: $(System.ArtifactsDirectory)/backend-drop/*.zip